version: '3.8'

services:
  db:
    image: postgres:16
    container_name: wishly-db
    restart: always
    environment:
      POSTGRES_USER: wishly
      POSTGRES_PASSWORD: wishlypassword
      POSTGRES_DB: wishly
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
